
import java.awt.Color;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import teletubies.Employee;
import teletubies.database.DatabaseHandler;
import teletubies.model.EmployeeDB;
import teletubies.model.EmployeeTable;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
/**
 *
 * @author Hall_PC
 */
public class EmployeePanel extends javax.swing.JPanel {

    /**
     * Creates new form ReportEmpPanel
     */
    public EmployeePanel() {
        initComponents();
        empGen();

    }

    //Show employee on gui
    public void empGen() {
        DefaultTableModel tableModel = (DefaultTableModel) showEmpTable.getModel();
        tableModel.setRowCount(0);
        try {
            ArrayList<EmployeeDB> employeeDBs = DatabaseHandler.findAllEmployee(new DatabaseHandler());
            for (int i = 0; i < employeeDBs.size(); i++) {
                tableModel.addRow(new Object[]{employeeDBs.get(i).getEmployeeID(),
                    employeeDBs.get(i).getFirstName(),
                    employeeDBs.get(i).getLastName(),
                    employeeDBs.get(i).getPhoneNumber(),
                    employeeDBs.get(i).getAddress(),
                    employeeDBs.get(i).getEmployeeLevel()});
            }
        } catch (Exception e) {
            System.err.println("Error!");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Title = new javax.swing.JLabel();
        insertEmpPanel = new javax.swing.JPanel();
        textEmp = new javax.swing.JLabel();
        inputEmp = new javax.swing.JTextField();
        title = new javax.swing.JLabel();
        firstNameText = new javax.swing.JLabel();
        inputFirstName = new javax.swing.JTextField();
        lastNameText = new javax.swing.JLabel();
        inputLastname = new javax.swing.JTextField();
        passwordText = new javax.swing.JLabel();
        inputPassword = new javax.swing.JTextField();
        ageText = new javax.swing.JLabel();
        inputAge = new javax.swing.JTextField();
        addressText = new javax.swing.JLabel();
        inputAddress = new javax.swing.JTextField();
        workText = new javax.swing.JLabel();
        InputWork = new javax.swing.JTextField();
        LevelText = new javax.swing.JLabel();
        addButton = new javax.swing.JButton();
        Phone = new javax.swing.JLabel();
        InputPhone = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        removeEmpPanel = new javax.swing.JPanel();
        removeEmpText = new javax.swing.JLabel();
        inputRemoveEmp = new javax.swing.JTextField();
        removeButton = new javax.swing.JButton();
        RemoveTitle = new javax.swing.JLabel();
        cookingTableScrollPane = new javax.swing.JScrollPane();
        showEmpTable = new javax.swing.JTable();

        setLayout(null);

        Title.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        Title.setText("Manage Employee");
        add(Title);
        Title.setBounds(130, 10, 420, 80);

        insertEmpPanel.setBackground(new java.awt.Color(204, 204, 204));
        insertEmpPanel.setLayout(null);

        textEmp.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        textEmp.setText("Employee ID");
        insertEmpPanel.add(textEmp);
        textEmp.setBounds(20, 50, 120, 30);

        inputEmp.setForeground(new java.awt.Color(153, 153, 153));
        inputEmp.setText("0001");
        inputEmp.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        inputEmp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                inputEmpMouseClicked(evt);
            }
        });
        inputEmp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                inputEmpKeyTyped(evt);
            }
        });
        insertEmpPanel.add(inputEmp);
        inputEmp.setBounds(20, 90, 270, 40);

        title.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        title.setForeground(new java.awt.Color(0, 102, 255));
        title.setText("Register Employee");
        insertEmpPanel.add(title);
        title.setBounds(210, 10, 220, 40);

        firstNameText.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        firstNameText.setText("FirstName");
        insertEmpPanel.add(firstNameText);
        firstNameText.setBounds(20, 130, 120, 30);

        inputFirstName.setForeground(new java.awt.Color(153, 153, 153));
        inputFirstName.setText("John");
        inputFirstName.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        inputFirstName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                inputFirstNameMouseClicked(evt);
            }
        });
        inputFirstName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputFirstNameActionPerformed(evt);
            }
        });
        insertEmpPanel.add(inputFirstName);
        inputFirstName.setBounds(20, 170, 270, 40);

        lastNameText.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lastNameText.setText("LastName");
        insertEmpPanel.add(lastNameText);
        lastNameText.setBounds(320, 130, 120, 30);

        inputLastname.setForeground(new java.awt.Color(153, 153, 153));
        inputLastname.setText("Good");
        inputLastname.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        inputLastname.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                inputLastnameMouseClicked(evt);
            }
        });
        inputLastname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputLastnameActionPerformed(evt);
            }
        });
        insertEmpPanel.add(inputLastname);
        inputLastname.setBounds(320, 170, 270, 40);

        passwordText.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        passwordText.setText("password");
        insertEmpPanel.add(passwordText);
        passwordText.setBounds(20, 210, 120, 30);

        inputPassword.setForeground(new java.awt.Color(153, 153, 153));
        inputPassword.setText("John123456");
        inputPassword.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        inputPassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                inputPasswordMouseClicked(evt);
            }
        });
        inputPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputPasswordActionPerformed(evt);
            }
        });
        inputPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                inputPasswordKeyTyped(evt);
            }
        });
        insertEmpPanel.add(inputPassword);
        inputPassword.setBounds(20, 250, 270, 40);

        ageText.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        ageText.setText("Age");
        insertEmpPanel.add(ageText);
        ageText.setBounds(20, 300, 120, 30);

        inputAge.setForeground(new java.awt.Color(153, 153, 153));
        inputAge.setText("18");
        inputAge.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        inputAge.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                inputAgeMouseClicked(evt);
            }
        });
        inputAge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputAgeActionPerformed(evt);
            }
        });
        inputAge.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                inputAgeKeyTyped(evt);
            }
        });
        insertEmpPanel.add(inputAge);
        inputAge.setBounds(20, 340, 270, 40);

        addressText.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        addressText.setText("Address");
        insertEmpPanel.add(addressText);
        addressText.setBounds(320, 300, 120, 30);

        inputAddress.setForeground(new java.awt.Color(153, 153, 153));
        inputAddress.setText("bangkok 101/40");
        inputAddress.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        inputAddress.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                inputAddressMouseClicked(evt);
            }
        });
        inputAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputAddressActionPerformed(evt);
            }
        });
        insertEmpPanel.add(inputAddress);
        inputAddress.setBounds(320, 340, 270, 40);

        workText.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        workText.setText("WorkStatus");
        insertEmpPanel.add(workText);
        workText.setBounds(20, 390, 190, 30);

        InputWork.setEditable(false);
        InputWork.setText("work");
        InputWork.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        InputWork.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                InputWorkMouseClicked(evt);
            }
        });
        InputWork.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputWorkActionPerformed(evt);
            }
        });
        insertEmpPanel.add(InputWork);
        InputWork.setBounds(20, 430, 270, 40);

        LevelText.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        LevelText.setText("Level of Work");
        insertEmpPanel.add(LevelText);
        LevelText.setBounds(320, 390, 200, 30);

        addButton.setBackground(new java.awt.Color(0, 102, 255));
        addButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        addButton.setForeground(new java.awt.Color(255, 255, 255));
        addButton.setText("ADD");
        addButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });
        insertEmpPanel.add(addButton);
        addButton.setBounds(450, 490, 145, 46);

        Phone.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        Phone.setText("Phone Number");
        Phone.setToolTipText("");
        insertEmpPanel.add(Phone);
        Phone.setBounds(320, 210, 120, 30);

        InputPhone.setForeground(new java.awt.Color(153, 153, 153));
        InputPhone.setText("0123456789");
        InputPhone.setDisabledTextColor(new java.awt.Color(153, 153, 153));
        InputPhone.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                InputPhoneMouseClicked(evt);
            }
        });
        InputPhone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                InputPhoneKeyTyped(evt);
            }
        });
        insertEmpPanel.add(InputPhone);
        InputPhone.setBounds(320, 250, 270, 40);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Level 1", "Level 2" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        insertEmpPanel.add(jComboBox1);
        jComboBox1.setBounds(320, 430, 270, 40);

        add(insertEmpPanel);
        insertEmpPanel.setBounds(620, 10, 620, 560);

        removeEmpPanel.setBackground(new java.awt.Color(204, 204, 204));
        removeEmpPanel.setLayout(null);

        removeEmpText.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        removeEmpText.setText("ID employee");
        removeEmpPanel.add(removeEmpText);
        removeEmpText.setBounds(250, 10, 110, 30);

        inputRemoveEmp.setForeground(new java.awt.Color(153, 153, 153));
        inputRemoveEmp.setText("0001");
        inputRemoveEmp.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        inputRemoveEmp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                inputRemoveEmpMouseClicked(evt);
            }
        });
        inputRemoveEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputRemoveEmpActionPerformed(evt);
            }
        });
        inputRemoveEmp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                inputRemoveEmpKeyTyped(evt);
            }
        });
        removeEmpPanel.add(inputRemoveEmp);
        inputRemoveEmp.setBounds(250, 40, 170, 50);

        removeButton.setBackground(new java.awt.Color(255, 0, 0));
        removeButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        removeButton.setForeground(new java.awt.Color(255, 255, 255));
        removeButton.setText("REMOVE");
        removeButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        removeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeButtonActionPerformed(evt);
            }
        });
        removeEmpPanel.add(removeButton);
        removeButton.setBounds(450, 40, 145, 46);

        RemoveTitle.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        RemoveTitle.setForeground(new java.awt.Color(255, 0, 0));
        RemoveTitle.setText("Remove Employee");
        removeEmpPanel.add(RemoveTitle);
        RemoveTitle.setBounds(20, 40, 220, 40);

        add(removeEmpPanel);
        removeEmpPanel.setBounds(620, 580, 620, 120);

        showEmpTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "EmployeeID", "FirstName", "LastName", "PhoneNumber", "Address", "EmployeeLevel"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        showEmpTable.setAlignmentX(-10.0F);
        showEmpTable.setGridColor(new java.awt.Color(0, 102, 255));
        showEmpTable.setRowHeight(40);
        showEmpTable.setRowMargin(5);
        cookingTableScrollPane.setViewportView(showEmpTable);

        add(cookingTableScrollPane);
        cookingTableScrollPane.setBounds(20, 110, 590, 590);
    }// </editor-fold>//GEN-END:initComponents

    //press button to add employee to database and refresh data on gui
    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        // TODO add your handling code here:
        try {
            EmployeeDB emp = new EmployeeDB();
            boolean isClickedAll = clicked[0] && clicked[1] && clicked[2] && clicked[3] && clicked[4] && clicked[5] && clicked[6];
            if (!isClickedAll) 
            {
                JOptionPane.showMessageDialog(null, "Please Enter All Data", "Error", JOptionPane.WARNING_MESSAGE);
            }
            else if (DatabaseHandler.findEmployeeById(new DatabaseHandler(), Integer.parseInt(inputEmp.getText())) == null)
            {
            emp.setEmployeeID(Integer.parseInt(inputEmp.getText()));
            emp.setFirstName(inputFirstName.getText());
            emp.setLastName(inputLastname.getText());
            emp.setPasswordEmp(inputPassword.getText());
            emp.setAge(Integer.parseInt(inputAge.getText()));
            emp.setAddress(inputAddress.getText());
            emp.setPhoneNumber(InputPhone.getText());
            emp.setWorkStatus(InputWork.getText());
            emp.setEmployeeLevel(jComboBox1.getSelectedIndex()+1);
            DatabaseHandler.insertEmployee(new DatabaseHandler(), emp);
            empGen();
            } else {
                JOptionPane.showMessageDialog(null, "ID Already Exist", "Error", JOptionPane.WARNING_MESSAGE);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e, "Error", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_addButtonActionPerformed

    private void inputRemoveEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputRemoveEmpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputRemoveEmpActionPerformed

    //press button to remove employee to database and refresh data on gui
    private void removeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeButtonActionPerformed
        // TODO add your handling code here:
        try {
                EmployeeDB emp = DatabaseHandler.findEmployeeById(new DatabaseHandler(), Integer.parseInt(inputRemoveEmp.getText()));
                if (emp.getEmployeeLevel() < 3)
                {
                DatabaseHandler.removeEmployee(new DatabaseHandler(), emp);
                } else {
                    JOptionPane.showMessageDialog(null, "Can't Delete Manager", "Error", JOptionPane.WARNING_MESSAGE);
                }
                empGen();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error", "Error", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_removeButtonActionPerformed

    private void inputLastnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputLastnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputLastnameActionPerformed

    private void inputPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputPasswordActionPerformed

    private void inputAgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputAgeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputAgeActionPerformed

    private void inputAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputAddressActionPerformed

    private void InputWorkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputWorkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InputWorkActionPerformed

    private void inputAgeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inputAgeMouseClicked
        // TODO add your handling code here:
        clicked[5] = true;
        inputAge.setText("");
        inputAge.setEditable(true);
        inputAge.setForeground(Color.black);
    }//GEN-LAST:event_inputAgeMouseClicked

    private void inputEmpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inputEmpMouseClicked
        // TODO add your handling code here:
        clicked[0] = true;
        inputEmp.setText("");
        inputEmp.setEditable(true);
        inputEmp.setForeground(Color.black);
    }//GEN-LAST:event_inputEmpMouseClicked

    private void inputFirstNameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inputFirstNameMouseClicked
        // TODO add your handling code here:
        clicked[1] = true;
        inputFirstName.setText("");
        inputFirstName.setEditable(true);
        inputFirstName.setForeground(Color.black);
    }//GEN-LAST:event_inputFirstNameMouseClicked

    private void inputLastnameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inputLastnameMouseClicked
        // TODO add your handling code here:
        clicked[2] = true;
        inputLastname.setText("");
        inputLastname.setEditable(true);
        inputLastname.setForeground(Color.black);
    }//GEN-LAST:event_inputLastnameMouseClicked

    private void inputPasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inputPasswordMouseClicked
        // TODO add your handling code here:
        clicked[3] = true;
        inputPassword.setText("");
        inputPassword.setEditable(true);
        inputPassword.setForeground(Color.black);
    }//GEN-LAST:event_inputPasswordMouseClicked

    private void inputAddressMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inputAddressMouseClicked
        // TODO add your handling code here:
        clicked[6] = true;
        inputAddress.setText("");
        inputAddress.setEditable(true);
        inputAddress.setForeground(Color.black);
    }//GEN-LAST:event_inputAddressMouseClicked

    private void InputWorkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InputWorkMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_InputWorkMouseClicked

    private void inputRemoveEmpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inputRemoveEmpMouseClicked
        // TODO add your handling code here:
        inputRemoveEmp.setText("");
        inputRemoveEmp.setEditable(true);
        inputRemoveEmp.setForeground(Color.black);
    }//GEN-LAST:event_inputRemoveEmpMouseClicked

    private void InputPhoneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InputPhoneMouseClicked
        // TODO add your handling code here:
        clicked[4] = true;
        InputPhone.setText("");
        InputPhone.setEditable(true);
        InputPhone.setForeground(Color.black);
    }//GEN-LAST:event_InputPhoneMouseClicked

    private void inputFirstNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputFirstNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputFirstNameActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void inputEmpKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inputEmpKeyTyped
        char enter = evt.getKeyChar();
        if(!(Character.isDigit(enter))){
            evt.consume();
            JOptionPane.showMessageDialog(null, "You can't enter alphabets here", "Error", JOptionPane.WARNING_MESSAGE);
        } 
    }//GEN-LAST:event_inputEmpKeyTyped

    private void inputAgeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inputAgeKeyTyped
        char enter = evt.getKeyChar();
        if(!(Character.isDigit(enter))){
            evt.consume();
            JOptionPane.showMessageDialog(null, "You can't enter alphabets here", "Error", JOptionPane.WARNING_MESSAGE);
        } 
    }//GEN-LAST:event_inputAgeKeyTyped

    private void InputPhoneKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_InputPhoneKeyTyped
        char enter = evt.getKeyChar();
        if(!(Character.isDigit(enter))){
            evt.consume();
            JOptionPane.showMessageDialog(null, "You can't enter alphabets here", "Error", JOptionPane.WARNING_MESSAGE);
        } 
    }//GEN-LAST:event_InputPhoneKeyTyped

    private void inputPasswordKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inputPasswordKeyTyped
        char enter = evt.getKeyChar();
        if(!(Character.isDigit(enter))){
            evt.consume();
            JOptionPane.showMessageDialog(null, "You can't enter alphabets here", "Error", JOptionPane.WARNING_MESSAGE);
        } 
    }//GEN-LAST:event_inputPasswordKeyTyped

    private void inputRemoveEmpKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inputRemoveEmpKeyTyped
       char enter = evt.getKeyChar();
        if(!(Character.isDigit(enter))){
            evt.consume();
            JOptionPane.showMessageDialog(null, "You can't enter alphabets here", "Error", JOptionPane.WARNING_MESSAGE);
        } 
    }//GEN-LAST:event_inputRemoveEmpKeyTyped

    private boolean[] clicked = {false,false,false,false,false,false,false,false};
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField InputPhone;
    private javax.swing.JTextField InputWork;
    private javax.swing.JLabel LevelText;
    private javax.swing.JLabel Phone;
    private javax.swing.JLabel RemoveTitle;
    private javax.swing.JLabel Title;
    private javax.swing.JButton addButton;
    private javax.swing.JLabel addressText;
    private javax.swing.JLabel ageText;
    private javax.swing.JScrollPane cookingTableScrollPane;
    private javax.swing.JLabel firstNameText;
    private javax.swing.JTextField inputAddress;
    private javax.swing.JTextField inputAge;
    private javax.swing.JTextField inputEmp;
    private javax.swing.JTextField inputFirstName;
    private javax.swing.JTextField inputLastname;
    private javax.swing.JTextField inputPassword;
    private javax.swing.JTextField inputRemoveEmp;
    private javax.swing.JPanel insertEmpPanel;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel lastNameText;
    private javax.swing.JLabel passwordText;
    private javax.swing.JButton removeButton;
    private javax.swing.JPanel removeEmpPanel;
    private javax.swing.JLabel removeEmpText;
    private javax.swing.JTable showEmpTable;
    private javax.swing.JLabel textEmp;
    private javax.swing.JLabel title;
    private javax.swing.JLabel workText;
    // End of variables declaration//GEN-END:variables
}
