
import javax.swing.JPanel;
import teletubies.Order;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author Hall_PC
 */
public class KitchenPanel extends javax.swing.JPanel {

    /**
     * Creates new form Kitchen
     */
    
    public KitchenPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        QueueTitle = new javax.swing.JLabel();
        kitchenQueuePanel = new javax.swing.JPanel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1280, 820));
        setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 20));

        QueueTitle.setFont(new java.awt.Font("Segoe UI", 1, 40)); // NOI18N
        QueueTitle.setText("Kitchen Queue");
        QueueTitle.setToolTipText("");
        add(QueueTitle);

        kitchenQueuePanel.setBackground(new java.awt.Color(255, 255, 255));
        kitchenQueuePanel.setAlignmentX(0.0F);
        kitchenQueuePanel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        kitchenQueuePanel.setMaximumSize(new java.awt.Dimension(32767, 720));
        kitchenQueuePanel.setPreferredSize(new java.awt.Dimension(1280, 660));
        kitchenQueuePanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 50, 5));
        add(kitchenQueuePanel);
    }// </editor-fold>//GEN-END:initComponents

    public void addOrder(Order order){
        kitchenQueuePanel.add(new OrderPanel(order));
    }
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel QueueTitle;
    private javax.swing.JPanel kitchenQueuePanel;
    // End of variables declaration//GEN-END:variables
}
