
import java.awt.CardLayout;
import javax.swing.JPanel;
import javax.swing.JPasswordField;
import javax.swing.JTextField;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author Hall_PC
 */
public class ManagerPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManagerPanel
     */
    public ManagerPanel() {
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleLabel = new javax.swing.JLabel();
        logOutButton = new javax.swing.JButton();
        managerButton = new javax.swing.JButton();
        reportSaleButton = new javax.swing.JButton();
        reportSaleDailyButton = new javax.swing.JButton();
        reportEmpButton = new javax.swing.JButton();

        setLayout(null);

        titleLabel.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        titleLabel.setText("Manager");
        add(titleLabel);
        titleLabel.setBounds(530, 10, 220, 80);

        logOutButton.setBackground(new java.awt.Color(255, 51, 51));
        logOutButton.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        logOutButton.setForeground(new java.awt.Color(255, 255, 255));
        logOutButton.setText("Logout");
        logOutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logOutButtonActionPerformed(evt);
            }
        });
        add(logOutButton);
        logOutButton.setBounds(1100, 40, 150, 40);

        managerButton.setBackground(new java.awt.Color(51, 51, 255));
        managerButton.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        managerButton.setForeground(new java.awt.Color(255, 255, 255));
        managerButton.setText("Manage Employee");
        managerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                managerButtonActionPerformed(evt);
            }
        });
        add(managerButton);
        managerButton.setBounds(510, 260, 260, 100);

        reportSaleButton.setBackground(new java.awt.Color(0, 102, 255));
        reportSaleButton.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        reportSaleButton.setForeground(new java.awt.Color(255, 255, 255));
        reportSaleButton.setText("Report Sale");
        reportSaleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reportSaleButtonActionPerformed(evt);
            }
        });
        add(reportSaleButton);
        reportSaleButton.setBounds(550, 510, 200, 100);

        reportSaleDailyButton.setBackground(new java.awt.Color(0, 102, 255));
        reportSaleDailyButton.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        reportSaleDailyButton.setForeground(new java.awt.Color(255, 255, 255));
        reportSaleDailyButton.setText("Report Sale daily");
        reportSaleDailyButton.setActionCommand("Report Sell daily");
        reportSaleDailyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reportSaleDailyButtonActionPerformed(evt);
            }
        });
        add(reportSaleDailyButton);
        reportSaleDailyButton.setBounds(790, 510, 290, 100);

        reportEmpButton.setBackground(new java.awt.Color(0, 102, 255));
        reportEmpButton.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        reportEmpButton.setForeground(new java.awt.Color(255, 255, 255));
        reportEmpButton.setText("Report employee");
        reportEmpButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reportEmpButtonActionPerformed(evt);
            }
        });
        add(reportEmpButton);
        reportEmpButton.setBounds(240, 510, 260, 100);
    }// </editor-fold>//GEN-END:initComponents

    private void reportSaleDailyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reportSaleDailyButtonActionPerformed
        ShowFrame reportEmp = new ShowFrame();
       reportEmp.showFrame(3);
    }//GEN-LAST:event_reportSaleDailyButtonActionPerformed

    private void managerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_managerButtonActionPerformed
         ShowFrame reportEmp = new ShowFrame();
        reportEmp.showFrame(4);
    }//GEN-LAST:event_managerButtonActionPerformed

    private void reportSaleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reportSaleButtonActionPerformed
        ShowFrame reportEmp = new ShowFrame();
       reportEmp.showFrame(2);
    }//GEN-LAST:event_reportSaleButtonActionPerformed

    private void reportEmpButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reportEmpButtonActionPerformed
       ShowFrame reportEmp = new ShowFrame();
       reportEmp.showFrame(1);
    }//GEN-LAST:event_reportEmpButtonActionPerformed

    private void logOutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logOutButtonActionPerformed
JPanel contain = (JPanel)getParent();
        CardLayout card = (CardLayout)contain.getLayout();
        card.show(contain,"loginPage");
        JPanel loginPage = (JPanel)contain.getComponent(0);
        JTextField inputID = (JTextField)loginPage.getComponent(2);
        JPasswordField inputPass = (JPasswordField)loginPage.getComponent(5);
        inputID.setText("");
        inputPass.setText("");
    }//GEN-LAST:event_logOutButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton logOutButton;
    private javax.swing.JButton managerButton;
    private javax.swing.JButton reportEmpButton;
    private javax.swing.JButton reportSaleButton;
    private javax.swing.JButton reportSaleDailyButton;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
}
