
import javax.swing.table.DefaultTableModel;
import teletubies.Order;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author Hall_PC
 */
public class QueueCustomerPanel extends javax.swing.JPanel {

    /**
     * Creates new form QueueCustomerPanel
     */
    
    public QueueCustomerPanel() {
        initComponents();
    }
    
    public static void removeCookingTable(int id){
        String s = String.format("#%04d", id);
        DefaultTableModel dt = (DefaultTableModel) cookingTable.getModel();
        for(int row = 0 ; row < cookingTable.getRowCount() ; row++){
            if(s.equals(cookingTable.getValueAt(row, 1))){
                dt.removeRow(cookingTable.convertRowIndexToModel(row));
            }
        }
    }
    
    
    public static void addCookingTable(Order order){
        DefaultTableModel dt = (DefaultTableModel) cookingTable.getModel();
        int id = order.getOrderID();
        String s = String.format("#%04d", id);
        String a = "";
        
        dt.addRow(new Object[] { a , s , a});
        
    }
    
    public static void removeFinishedTable(int id){
        String s = String.format("#%04d", id);
        DefaultTableModel dt = (DefaultTableModel) finishTable.getModel();
        for(int row = 0 ; row < finishTable.getRowCount() ; row++){
            if(s.equals(finishTable.getValueAt(row, 1))){
                dt.removeRow(finishTable.convertRowIndexToModel(row));
            }
        }
    }
    
    
    public static void addFinishedTable(int id){
        DefaultTableModel dt = (DefaultTableModel) finishTable.getModel();
        String s = String.format("#%04d", id);
        String a = "";
        
        dt.addRow(new Object[] { " " , s , " "});
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cookingTableScrollPane = new javax.swing.JScrollPane();
        cookingTable = new javax.swing.JTable();
        queueTitle = new javax.swing.JLabel();
        finishText = new javax.swing.JLabel();
        finishTableScrollPane = new javax.swing.JScrollPane();
        finishTable = new javax.swing.JTable();
        cookingText = new javax.swing.JLabel();
        cookingIcon = new javax.swing.JLabel();
        FinishIcon = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1280, 720));
        setLayout(null);

        cookingTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "", "Order_ID Cooking", ""
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        cookingTable.setAlignmentX(-10.0F);
        cookingTable.setGridColor(new java.awt.Color(0, 102, 255));
        cookingTable.setRowHeight(40);
        cookingTable.setRowMargin(5);
        cookingTableScrollPane.setViewportView(cookingTable);

        add(cookingTableScrollPane);
        cookingTableScrollPane.setBounds(190, 220, 410, 430);

        queueTitle.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        queueTitle.setText("Order Queue");
        queueTitle.setToolTipText("");
        add(queueTitle);
        queueTitle.setBounds(540, 20, 300, 60);

        finishText.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        finishText.setForeground(new java.awt.Color(0, 102, 255));
        finishText.setText("Order Finish");
        finishText.setToolTipText("");
        add(finishText);
        finishText.setBounds(890, 170, 150, 40);

        finishTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "", "Order_ID Finish", ""
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        finishTable.setAlignmentX(-10.0F);
        finishTable.setRowHeight(40);
        finishTable.setRowMargin(5);
        finishTableScrollPane.setViewportView(finishTable);

        add(finishTableScrollPane);
        finishTableScrollPane.setBounds(760, 220, 410, 430);

        cookingText.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        cookingText.setForeground(new java.awt.Color(0, 102, 255));
        cookingText.setText("Order Cooking");
        cookingText.setToolTipText("");
        add(cookingText);
        cookingText.setBounds(310, 160, 170, 50);

        cookingIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cooking.png"))); // NOI18N
        cookingIcon.setText("jLabel5");
        add(cookingIcon);
        cookingIcon.setBounds(330, 40, 130, 120);

        FinishIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/finish.png"))); // NOI18N
        add(FinishIcon);
        FinishIcon.setBounds(900, 50, 120, 110);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel FinishIcon;
    private javax.swing.JLabel cookingIcon;
    private static javax.swing.JTable cookingTable;
    private javax.swing.JScrollPane cookingTableScrollPane;
    private javax.swing.JLabel cookingText;
    private static javax.swing.JTable finishTable;
    private javax.swing.JScrollPane finishTableScrollPane;
    private javax.swing.JLabel finishText;
    private javax.swing.JLabel queueTitle;
    // End of variables declaration//GEN-END:variables
}
