
import javax.swing.JTextArea;
import teletubies.Order;
import teletubies.Payment;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author acer
 */
public class Receipt extends javax.swing.JFrame {

    private String name;
    private Payment pay;
    private GetOrder gO;
    
    /**
     * Creates new form Receipt
     */
    public Receipt() {
        initComponents();
    }

    public Receipt(String name , Payment pay,GetOrder gO ) {
        this.name = name;
        this.pay = pay;
        this.gO = gO;
        initComponents();
        printBill(jTextArea1);
        gO.clearOrder();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Teletubbies Cafe");
        setResizable(false);

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane1.setPreferredSize(new java.awt.Dimension(1280, 720));

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setWrapStyleWord(true);
        jTextArea1.setPreferredSize(new java.awt.Dimension(1280, 720));
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Receipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Receipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Receipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Receipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Receipt().setVisible(true);
            }
        });
    }

    public void printBill(JTextArea b){
        try{
            Order order = pay.getOrder();
            b.setText("\t \tTeletubies Cafe \n");  //b mean bill textarea
            b.setText(b.getText()+"\t \tKMITL \n");
            b.setText(b.getText()+"\t \tEmployee : " + name + "\n");
            b.setText(b.getText()+"\t \tOrderID : " + order.getOrderID() + "\n");
            b.setText(b.getText()+"\t \tDate : " + order.getOrderDate()+ "\n");
            b.setText(b.getText()+"--------------------------------------------------------------------------------------------------------------------------\n");
            b.setText(b.getText()+"\tItem \t\tQty \tprice" + "\n");
            b.setText(b.getText()+"--------------------------------------------------------------------------------------------------------------------------\n");

            for(int i = 0 ; i < order.getFood().size(); i++){
                String name = order.getOrderFoodName().get(i);
                int qty = order.getOrderQuantity().get(i);
                int price = order.getFood().get(i).getfoodPrice()*qty;
                if (name.length() < 14){
                    b.setText(b.getText() + " "+ name +"\t\t\t" +qty +"\t"+ price + "\n");
                } else if (name.length() <= 30){
                    b.setText(b.getText() + " "+ name +"\t\t" +qty +"\t"+ price + "\n");
                } else {
                    b.setText(b.getText() + " "+ name +"\t" +qty +"\t"+ price + "\n");
                }
            }
           b.setText(b.getText() + "--------------------------------------------------------------------------------------------------------------------------\n");
           b.setText(b.getText() + " \t \tTotal : " + order.getTotalPrice() + "\n");       
           b.setText(b.getText() + "--------------------------------------------------------------------------------------------------------------------------\n");  
           b.setText(b.getText() + " \t \tThank for your business!\n");
        }catch(Exception e){
            e.printStackTrace();
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
