
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.Date;
import java.util.Locale;
import javax.swing.table.DefaultTableModel;
import teletubies.database.DatabaseHandler;
import teletubies.model.ReportSellDaliy;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
/**
 *
 * @author Hall_PC
 */
public class ReportSaledaily extends javax.swing.JPanel {

    /**
     * Creates new form ReportEmpPanel
     */
    public ReportSaledaily() {
        initComponents();
        reportGen();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cookingTableScrollPane = new javax.swing.JScrollPane();
        cookingTable = new javax.swing.JTable();
        reportSaleDailyTitleLabel = new javax.swing.JLabel();

        setLayout(null);

        cookingTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Order ID", "Emp ID", "FoodName", "Price", "Quatity", "totalPrice", "Sale TimeStamp"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        cookingTable.setAlignmentX(-10.0F);
        cookingTable.setGridColor(new java.awt.Color(0, 102, 255));
        cookingTable.setRowHeight(40);
        cookingTable.setRowMargin(5);
        cookingTableScrollPane.setViewportView(cookingTable);

        add(cookingTableScrollPane);
        cookingTableScrollPane.setBounds(40, 110, 1180, 550);

        reportSaleDailyTitleLabel.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        reportSaleDailyTitleLabel.setText("Report Sale Daily (02 Jan 2020)");
        add(reportSaleDailyTitleLabel);
        reportSaleDailyTitleLabel.setBounds(300, 20, 740, 80);
    }// </editor-fold>//GEN-END:initComponents

    //Show report sale daily on gui
    private void reportGen() {
        try {
            Date nowDate = new Date();//For reference
            SimpleDateFormat formatter = new SimpleDateFormat("yyyy-MM-dd", Locale.ENGLISH);
            String formattedString = formatter.format(nowDate);
            reportSaleDailyTitleLabel.setText("Report Sale Daily (" + formattedString + ")");
            DefaultTableModel tableModel = (DefaultTableModel) cookingTable.getModel();
            ArrayList<ReportSellDaliy> orderDailyTable = DatabaseHandler.findReportOrderByTime(new DatabaseHandler(), formattedString);
            int length = orderDailyTable.size();
            if (length > 0) {
                for (int i = 0; i < length; i++) {
                    tableModel.addRow(new Object[]{orderDailyTable.get(i).getOrderID(),
                        orderDailyTable.get(i).getEmployeeID(),
                        orderDailyTable.get(i).getFoodName(),
                        orderDailyTable.get(i).getFoodPrice(),
                        orderDailyTable.get(i).getQuantity(),
                        orderDailyTable.get(i).getTotalPrice(),
                        orderDailyTable.get(i).getSaleTimestamp()});
                }
            }
        } catch (Exception ex) {
            System.out.println("No order yet.");;
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable cookingTable;
    private javax.swing.JScrollPane cookingTableScrollPane;
    private javax.swing.JLabel reportSaleDailyTitleLabel;
    // End of variables declaration//GEN-END:variables
}
